/*    ==Paramètres de script==

    Version du serveur source : SQL Server 2016 (13.0.1601)
    Édition du moteur de base de données source : Microsoft SQL Server Enterprise Edition
    Type du moteur de base de données source : SQL Server autonome

    Version du serveur cible : SQL Server 2017
    Édition du moteur de base de données cible : Microsoft SQL Server Standard Edition
    Type du moteur de base de données cible : SQL Server autonome
*/

USE [master]
GO
/****** Object:  Database [AJBAQ]    Script Date: 01/04/2019 09:19:40 ******/
CREATE DATABASE [AJBAQ]
GO
ALTER DATABASE [AJBAQ] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AJBAQ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AJBAQ] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AJBAQ] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AJBAQ] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AJBAQ] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AJBAQ] SET ARITHABORT OFF 
GO
ALTER DATABASE [AJBAQ] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AJBAQ] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AJBAQ] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AJBAQ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AJBAQ] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AJBAQ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AJBAQ] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AJBAQ] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AJBAQ] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AJBAQ] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AJBAQ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AJBAQ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AJBAQ] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AJBAQ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AJBAQ] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AJBAQ] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AJBAQ] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AJBAQ] SET RECOVERY FULL 
GO
ALTER DATABASE [AJBAQ] SET  MULTI_USER 
GO
ALTER DATABASE [AJBAQ] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AJBAQ] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AJBAQ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AJBAQ] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AJBAQ] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'AJBAQ', N'ON'
GO
ALTER DATABASE [AJBAQ] SET QUERY_STORE = OFF
GO
USE [AJBAQ]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [AJBAQ]
GO
/****** Object:  Table [dbo].[Answer]    Script Date: 01/04/2019 09:19:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Answer](
	[answer_id] [int] NOT NULL,
	[user_id] [varchar](50) NOT NULL,
	[question_id] [int] NOT NULL,
	[choice_id] [int] NOT NULL,
	[answer_time] [datetime] NOT NULL,
 CONSTRAINT [PK_Answer] PRIMARY KEY CLUSTERED 
(
	[answer_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Choice]    Script Date: 01/04/2019 09:19:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Choice](
	[choice_id] [int] IDENTITY(1,1) NOT NULL,
	[question_id] [int] NOT NULL,
	[is_right_choice] [bit] NOT NULL,
	[choice] [varchar](max) NOT NULL,
 CONSTRAINT [PK_Choice] PRIMARY KEY CLUSTERED 
(
	[choice_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Question]    Script Date: 01/04/2019 09:19:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Question](
	[question_id] [int] IDENTITY(1,1) NOT NULL,
	[question] [varchar](max) NOT NULL,
 CONSTRAINT [PK_Question] PRIMARY KEY CLUSTERED 
(
	[question_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 01/04/2019 09:19:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[user_id] [varchar](50) NOT NULL,
	[username] [varchar](max) NOT NULL,
	[userpass] [varchar](max) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[user_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Answer]  WITH CHECK ADD  CONSTRAINT [FK_Answer_Choice] FOREIGN KEY([choice_id])
REFERENCES [dbo].[Choice] ([choice_id])
GO
ALTER TABLE [dbo].[Answer] CHECK CONSTRAINT [FK_Answer_Choice]
GO
ALTER TABLE [dbo].[Answer]  WITH CHECK ADD  CONSTRAINT [FK_Answer_Question] FOREIGN KEY([question_id])
REFERENCES [dbo].[Question] ([question_id])
GO
ALTER TABLE [dbo].[Answer] CHECK CONSTRAINT [FK_Answer_Question]
GO
ALTER TABLE [dbo].[Answer]  WITH CHECK ADD  CONSTRAINT [FK_Answer_User] FOREIGN KEY([user_id])
REFERENCES [dbo].[User] ([user_id])
GO
ALTER TABLE [dbo].[Answer] CHECK CONSTRAINT [FK_Answer_User]
GO
ALTER TABLE [dbo].[Choice]  WITH CHECK ADD  CONSTRAINT [FK_Choice_Question] FOREIGN KEY([question_id])
REFERENCES [dbo].[Question] ([question_id])
GO
ALTER TABLE [dbo].[Choice] CHECK CONSTRAINT [FK_Choice_Question]
GO
USE [master]
GO
ALTER DATABASE [AJBAQ] SET  READ_WRITE 
GO
